// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

import {defineConfig,env} from "prisma/config";
import "dotenv/config";

export default defineConfig({
    // path to your Prisma schema
    schema:"prisma/schema.prisma",

    // Database connection (used by migrate,db push,studio)
    datasource:{
        url:env("DATABASE_URL"),
    },

    //Migration settings
    migrations:{
        path:"prisma/migrations",
    }
})